name: Docker CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Actualizado a v4 que es la estable actual
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Eliminamos el paso "Authenticate Railway CLI" porque causaba el error
      # y pasamos el token directamente al comando de despliegue.

      - name: Deploy to Railway
        run: railway up --detach --service "dev-ecommerce-movil" # Opcional: --service ayuda si tienes varios
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}