name: Docker CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --detach --project "2b6cc09c-1d29-4d30-8dc1-06eb704e4092" --environment "production" --service "blissful-perception"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
